/* Axel settings, generated by configure */
#define _REENTRANT
#define _THREAD_SAFE
#define ETCDIR "/usr/local/etc"
#define LOCALE "/usr/local/share/locale"
#define ARCH "Linux"

#undef I18N
#undef THREAD_CANCEL
